version: '3.8'

services:
  deto-postgres:
    image: postgres:16-alpine
    container_name: deto-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: deto_db
    ports:
      - "5432:5432"
    volumes:
      - deto_pgdata:/var/lib/postgresql/data

volumes:
  deto_pgdata:
